spring:
  cloud:
    config:
      server:
        git:
          uri: file:/Users/m.gorelikov/Documents/workspace/training/cloud-config
  application:
    name: configserver

management:
  endpoints:
    web:
      exposure:
        include: '*'

server:
  port: 0
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9090/eureka/